extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
rules:
  semi: 'off'
  quotes: 'off'
  '@typescript-eslint/semi': error
  '@typescript-eslint/quotes':
    - error
    - single
